#!/bin/bash

# Dependencies: None

runhelp() {
    echo ""
    echo "Usage: find-files [[CONTEXT] [PATTERNS] ...] [FLAGS]"
    echo ""
    echo "  Find files based on criteria. Multiple sets of criteria may be"
    echo "  specified. All criteria must succeed to match a file."
    echo ""
    echo "CONTEXT:"
    echo "  -d|--dir DIRNAME"
    echo "      Must be within (directly or child dir or) matching DIRNAME"
    echo "  -D|--exact-dir DIRNAME"
    echo "      Must be directly within matching DIRNAME"
    echo "  -f|--filename FILE"
    echo "      Match against filename FILE"
    echo "PATTERNS:"
    echo "  -e|--equals FIELD:PATTERN"
    echo "      The given FIELD must exactly match PATTERN"
    echo "  -i|--equals-ci FIELD:PATTERN"
    echo "      The given FIELD must case-insensitively match PATTERN"
    echo "  -r|--regex FIELD:PATTERN"
    echo "      The given FIELD must RegEx match PATTERN"
    echo "  -a|--starts FIELD:PATTERN"
    echo "      The given FIELD must start with PATTERN"
    echo "  -A|--starts-ci FIELD:PATTERN"
    echo "      The given FIELD must case-insensitively start with PATTERN"
    echo "  -z|--ends FIELD:PATTERN"
    echo "      The given FIELD must end with PATTERN"
    echo "  -Z|--ends-ci FIELD:PATTERN"
    echo "      The given FIELD must case-insensitively end with PATTERN"
    echo "FLAGS:"
    echo "  -J|--json JSON"
    echo "      Write results to the file JSON."
    echo "  -v|--verbose"
    echo "      Display verbose output."
    echo ""
}

if [[ -z "$1" || $1 == "help" ]]; then
    runhelp
    exit 0
fi
