---
manifest:
  # String that can be used to identify row (used for separating output)
  id: "{{ basename }}"
  # Only run on rows in the manifest matching these parameters
  filter:
    # equals, startswith, endswith, regex, ignorecase
    - value: mediatype
      equals: video
      ignorecase: true
  # For each manifest row, match the following files
  files:
    - label: pres
      # value: "{{ file.name }}"    # Default for files section
      startswith: "{{ basename }}"
      regex: '(?:_pres\.mov|\.mkv)$'
    - label: mezz
      startswith: "{{ basename }}"
      regex: '(?<!_pres)\.mov$'
    - label: access
      startswith: "{{ basename }}"
      regex: '(?:_access\.mov|\.mp4)$'
    - label: pres_hash
      startswith: "{{ basename }}"
      regex: '(?:_pres\.mov|\.mkv)\.md5$'
    - label: mezz_hash
      startswith: "{{ basename }}"
      regex: '(?<!_pres)\.mov\.md5$'
    - label: access_hash
      startswith: "{{ basename }}"
      regex: '(?:_access\.mov|\.mp4)\.md5$'
    - label: mods
      startswith: "{{ basename }}"
      endswith: '_MODS.xml'
    - label: asset
      multiple: true
      optional: true
      startswith: "{{ basename }}"
      regex: '_Asset.*\.tif$'
    - label: asset_hash
      linkedto: asset
      startswith: "{{ asset | basename }}"
      endswith: '.md5'
    - label: ephemera
      multiple: true
      optional: true
      startswith: "{{ basename }}"
      regex: '_Ephemera.*\.tif$'
    - label: ephemera_hash
      linkedto: ephemera
      startswith: "{{ ephemera | basename }}"
      endswith: '.md5'

stages:
  # Run access hash check
  stage1.1:
    script: "scripts/verify-hash -c {{ access }} -f {{ access_hash }} -v -J {{ results_path }}"
  # Run mezzanine hash check
  stage1.2:
    script: "scripts/verify-hash -c {{ mezz }} -f {{ mezz_hash }} -v -J {{ results_path }}"
  # Run preservation hash check
  stage1.3:
    script: "scripts/verify-hash -c {{ pres }} -f {{ pres_hash }} -v -J {{ results_path }}"
  # TODO handle duplicate stage declarations TODO
  #stage1.3:
  #  script: "scripts/verify-hash -c {{ pres }} -f {{ pres_hash }} -v -J {{ results_path }}"
  # Run assets hash check
  stage1.4:
    script: "scripts/verify-hash -c {{ asset }} -f {{ asset_hash }} -v -J {{ results_path }}"
    loopvars:
      - asset
      - asset_hash
  # Run ephemera hash check
  stage1.5:
    script: "scripts/verify-hash -c {{ ephemera }} -f {{ ephemera_hash }} -v -J {{ results_path }}"
    loopvars:
      - ephemera
      - ephemera_hash

  # Verify file fingerprint
  #stage2.1:
  #  script: "echo TODO"

  # Verify video frames
  #stage3.1:
  #  script: "echo TODO"
