---
manifest:
  # Only run on rows in the manifest matching these parameters
  filter:
    # equals, matches(caseinsensitive equals), startswith, endswith, regex
    - label: mediatype
      matches: video
  # For each manifest row, match the following files
  files:
    - label: pres
      startswith: "{{ basename }}"
      regex: '(?:_pres.mov|.mkv)$'
    - label: mezz
      startswith: "{{ basename }}"
      regex: '(?<!_pres).mov$'
    - label: access
      startswith: "{{ basename }}"
      regex: '(?:_access.mov|.mp4)$'
    - label: pres_hash
      startswith: "{{ basename }}"
      regex: '(?:_pres.mov|.mkv).md5$'
    - label: mezz_hash
      startswith: "{{ basename }}"
      regex: '(?<!_pres).mov.md5$'
    - label: access_hash
      startswith: "{{ basename }}"
      regex: '(?:_access.mov|.mp4).md5$'
    - label: mods
      startswith: "{{ basename }}"
      endswith: '_MODS.xml'
    - label: assets
      multiple: true
      optional: true
      startswith: "{{ basename }}"
      regex: '_Asset.+\.tif$'

stages:
  # Run a file hash check
  stage1:
    script: "scripts/verify-hash -c {{ filename }}"

  # Verify file fingerprint
  stage2:
    script: "sleep 1"

  # Verify video frames
